language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t lucasrombaldi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lucasrombaldi/docker-react npm run test
